//! The VA-API FFI structures against the C compiler's view of libva's headers (libva 2.24,
//! VA-API 1.24): sizes, alignments, field offsets, constants and the bit-field packing of the
//! H.264 picture parameters. Generated by compiling a C program (gcc, x86-64 Linux) that includes
//! `<va/va.h>` and prints `sizeof` / `offsetof` / the constants for every declaration in `ffi.rs`;
//! the headers are MIT-licensed and not in this repository.
#![allow(clippy::unreadable_literal)]

use super::ffi::*;
use std::mem::{align_of, offset_of, size_of};

#[test]
fn layouts_and_constants_match_the_header() {
    assert_eq!((size_of::<VAConfigAttrib>(), align_of::<VAConfigAttrib>()), (8, 4), "VAConfigAttrib");
    assert_eq!(offset_of!(VAConfigAttrib, type_), 0, "VAConfigAttrib.type_");
    assert_eq!(offset_of!(VAConfigAttrib, value), 4, "VAConfigAttrib.value");
    assert_eq!((size_of::<VAImageFormat>(), align_of::<VAImageFormat>()), (48, 4), "VAImageFormat");
    assert_eq!(offset_of!(VAImageFormat, fourcc), 0, "VAImageFormat.fourcc");
    assert_eq!(offset_of!(VAImageFormat, depth), 12, "VAImageFormat.depth");
    assert_eq!(offset_of!(VAImageFormat, alpha_mask), 28, "VAImageFormat.alpha_mask");
    assert_eq!(offset_of!(VAImageFormat, va_reserved), 32, "VAImageFormat.va_reserved");
    assert_eq!((size_of::<VAImage>(), align_of::<VAImage>()), (120, 4), "VAImage");
    assert_eq!(offset_of!(VAImage, image_id), 0, "VAImage.image_id");
    assert_eq!(offset_of!(VAImage, format), 4, "VAImage.format");
    assert_eq!(offset_of!(VAImage, buf), 52, "VAImage.buf");
    assert_eq!(offset_of!(VAImage, width), 56, "VAImage.width");
    assert_eq!(offset_of!(VAImage, height), 58, "VAImage.height");
    assert_eq!(offset_of!(VAImage, data_size), 60, "VAImage.data_size");
    assert_eq!(offset_of!(VAImage, num_planes), 64, "VAImage.num_planes");
    assert_eq!(offset_of!(VAImage, pitches), 68, "VAImage.pitches");
    assert_eq!(offset_of!(VAImage, offsets), 80, "VAImage.offsets");
    assert_eq!(offset_of!(VAImage, num_palette_entries), 92, "VAImage.num_palette_entries");
    assert_eq!(offset_of!(VAImage, entry_bytes), 96, "VAImage.entry_bytes");
    assert_eq!(offset_of!(VAImage, component_order), 100, "VAImage.component_order");
    assert_eq!(offset_of!(VAImage, va_reserved), 104, "VAImage.va_reserved");
    assert_eq!((size_of::<VAPictureH264>(), align_of::<VAPictureH264>()), (36, 4), "VAPictureH264");
    assert_eq!(offset_of!(VAPictureH264, picture_id), 0, "VAPictureH264.picture_id");
    assert_eq!(offset_of!(VAPictureH264, frame_idx), 4, "VAPictureH264.frame_idx");
    assert_eq!(offset_of!(VAPictureH264, flags), 8, "VAPictureH264.flags");
    assert_eq!(offset_of!(VAPictureH264, TopFieldOrderCnt), 12, "VAPictureH264.TopFieldOrderCnt");
    assert_eq!(offset_of!(VAPictureH264, BottomFieldOrderCnt), 16, "VAPictureH264.BottomFieldOrderCnt");
    assert_eq!(offset_of!(VAPictureH264, va_reserved), 20, "VAPictureH264.va_reserved");
    assert_eq!((size_of::<VAPictureParameterBufferH264>(), align_of::<VAPictureParameterBufferH264>()), (672, 4), "VAPictureParameterBufferH264");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, CurrPic), 0, "VAPictureParameterBufferH264.CurrPic");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, ReferenceFrames), 36, "VAPictureParameterBufferH264.ReferenceFrames");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, picture_width_in_mbs_minus1), 612, "VAPictureParameterBufferH264.picture_width_in_mbs_minus1");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, picture_height_in_mbs_minus1), 614, "VAPictureParameterBufferH264.picture_height_in_mbs_minus1");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, bit_depth_luma_minus8), 616, "VAPictureParameterBufferH264.bit_depth_luma_minus8");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, bit_depth_chroma_minus8), 617, "VAPictureParameterBufferH264.bit_depth_chroma_minus8");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, num_ref_frames), 618, "VAPictureParameterBufferH264.num_ref_frames");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, seq_fields), 620, "VAPictureParameterBufferH264.seq_fields");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, num_slice_groups_minus1), 624, "VAPictureParameterBufferH264.num_slice_groups_minus1");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, slice_group_map_type), 625, "VAPictureParameterBufferH264.slice_group_map_type");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, slice_group_change_rate_minus1), 626, "VAPictureParameterBufferH264.slice_group_change_rate_minus1");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, pic_init_qp_minus26), 628, "VAPictureParameterBufferH264.pic_init_qp_minus26");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, pic_init_qs_minus26), 629, "VAPictureParameterBufferH264.pic_init_qs_minus26");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, chroma_qp_index_offset), 630, "VAPictureParameterBufferH264.chroma_qp_index_offset");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, second_chroma_qp_index_offset), 631, "VAPictureParameterBufferH264.second_chroma_qp_index_offset");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, pic_fields), 632, "VAPictureParameterBufferH264.pic_fields");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, frame_num), 636, "VAPictureParameterBufferH264.frame_num");
    assert_eq!(offset_of!(VAPictureParameterBufferH264, va_reserved), 640, "VAPictureParameterBufferH264.va_reserved");
    assert_eq!((size_of::<VAIQMatrixBufferH264>(), align_of::<VAIQMatrixBufferH264>()), (240, 4), "VAIQMatrixBufferH264");
    assert_eq!(offset_of!(VAIQMatrixBufferH264, ScalingList4x4), 0, "VAIQMatrixBufferH264.ScalingList4x4");
    assert_eq!(offset_of!(VAIQMatrixBufferH264, ScalingList8x8), 96, "VAIQMatrixBufferH264.ScalingList8x8");
    assert_eq!(offset_of!(VAIQMatrixBufferH264, va_reserved), 224, "VAIQMatrixBufferH264.va_reserved");
    assert_eq!((size_of::<VASliceParameterBufferH264>(), align_of::<VASliceParameterBufferH264>()), (3128, 4), "VASliceParameterBufferH264");
    assert_eq!(offset_of!(VASliceParameterBufferH264, slice_data_size), 0, "VASliceParameterBufferH264.slice_data_size");
    assert_eq!(offset_of!(VASliceParameterBufferH264, slice_data_offset), 4, "VASliceParameterBufferH264.slice_data_offset");
    assert_eq!(offset_of!(VASliceParameterBufferH264, slice_data_flag), 8, "VASliceParameterBufferH264.slice_data_flag");
    assert_eq!(offset_of!(VASliceParameterBufferH264, slice_data_bit_offset), 12, "VASliceParameterBufferH264.slice_data_bit_offset");
    assert_eq!(offset_of!(VASliceParameterBufferH264, first_mb_in_slice), 14, "VASliceParameterBufferH264.first_mb_in_slice");
    assert_eq!(offset_of!(VASliceParameterBufferH264, slice_type), 16, "VASliceParameterBufferH264.slice_type");
    assert_eq!(offset_of!(VASliceParameterBufferH264, direct_spatial_mv_pred_flag), 17, "VASliceParameterBufferH264.direct_spatial_mv_pred_flag");
    assert_eq!(offset_of!(VASliceParameterBufferH264, num_ref_idx_l0_active_minus1), 18, "VASliceParameterBufferH264.num_ref_idx_l0_active_minus1");
    assert_eq!(offset_of!(VASliceParameterBufferH264, num_ref_idx_l1_active_minus1), 19, "VASliceParameterBufferH264.num_ref_idx_l1_active_minus1");
    assert_eq!(offset_of!(VASliceParameterBufferH264, cabac_init_idc), 20, "VASliceParameterBufferH264.cabac_init_idc");
    assert_eq!(offset_of!(VASliceParameterBufferH264, slice_qp_delta), 21, "VASliceParameterBufferH264.slice_qp_delta");
    assert_eq!(offset_of!(VASliceParameterBufferH264, disable_deblocking_filter_idc), 22, "VASliceParameterBufferH264.disable_deblocking_filter_idc");
    assert_eq!(offset_of!(VASliceParameterBufferH264, slice_alpha_c0_offset_div2), 23, "VASliceParameterBufferH264.slice_alpha_c0_offset_div2");
    assert_eq!(offset_of!(VASliceParameterBufferH264, slice_beta_offset_div2), 24, "VASliceParameterBufferH264.slice_beta_offset_div2");
    assert_eq!(offset_of!(VASliceParameterBufferH264, RefPicList0), 28, "VASliceParameterBufferH264.RefPicList0");
    assert_eq!(offset_of!(VASliceParameterBufferH264, RefPicList1), 1180, "VASliceParameterBufferH264.RefPicList1");
    assert_eq!(offset_of!(VASliceParameterBufferH264, luma_log2_weight_denom), 2332, "VASliceParameterBufferH264.luma_log2_weight_denom");
    assert_eq!(offset_of!(VASliceParameterBufferH264, chroma_log2_weight_denom), 2333, "VASliceParameterBufferH264.chroma_log2_weight_denom");
    assert_eq!(offset_of!(VASliceParameterBufferH264, luma_weight_l0_flag), 2334, "VASliceParameterBufferH264.luma_weight_l0_flag");
    assert_eq!(offset_of!(VASliceParameterBufferH264, luma_weight_l0), 2336, "VASliceParameterBufferH264.luma_weight_l0");
    assert_eq!(offset_of!(VASliceParameterBufferH264, luma_offset_l0), 2400, "VASliceParameterBufferH264.luma_offset_l0");
    assert_eq!(offset_of!(VASliceParameterBufferH264, chroma_weight_l0_flag), 2464, "VASliceParameterBufferH264.chroma_weight_l0_flag");
    assert_eq!(offset_of!(VASliceParameterBufferH264, chroma_weight_l0), 2466, "VASliceParameterBufferH264.chroma_weight_l0");
    assert_eq!(offset_of!(VASliceParameterBufferH264, chroma_offset_l0), 2594, "VASliceParameterBufferH264.chroma_offset_l0");
    assert_eq!(offset_of!(VASliceParameterBufferH264, luma_weight_l1_flag), 2722, "VASliceParameterBufferH264.luma_weight_l1_flag");
    assert_eq!(offset_of!(VASliceParameterBufferH264, luma_weight_l1), 2724, "VASliceParameterBufferH264.luma_weight_l1");
    assert_eq!(offset_of!(VASliceParameterBufferH264, luma_offset_l1), 2788, "VASliceParameterBufferH264.luma_offset_l1");
    assert_eq!(offset_of!(VASliceParameterBufferH264, chroma_weight_l1_flag), 2852, "VASliceParameterBufferH264.chroma_weight_l1_flag");
    assert_eq!(offset_of!(VASliceParameterBufferH264, chroma_weight_l1), 2854, "VASliceParameterBufferH264.chroma_weight_l1");
    assert_eq!(offset_of!(VASliceParameterBufferH264, chroma_offset_l1), 2982, "VASliceParameterBufferH264.chroma_offset_l1");
    assert_eq!(offset_of!(VASliceParameterBufferH264, va_reserved), 3112, "VASliceParameterBufferH264.va_reserved");
    assert_eq!(VA_STATUS_SUCCESS as i64, 0, "VA_STATUS_SUCCESS");
    assert_eq!(VA_INVALID_ID as i64, 4294967295, "VA_INVALID_ID");
    assert_eq!(VAProfileH264Main as i64, 6, "VAProfileH264Main");
    assert_eq!(VAProfileH264High as i64, 7, "VAProfileH264High");
    assert_eq!(VAProfileH264ConstrainedBaseline as i64, 13, "VAProfileH264ConstrainedBaseline");
    assert_eq!(VAProfileHEVCMain as i64, 17, "VAProfileHEVCMain");
    assert_eq!(VAProfileHEVCMain10 as i64, 18, "VAProfileHEVCMain10");
    assert_eq!(VAEntrypointVLD as i64, 1, "VAEntrypointVLD");
    assert_eq!(VAConfigAttribRTFormat as i64, 0, "VAConfigAttribRTFormat");
    assert_eq!(VAConfigAttribMaxPictureWidth as i64, 18, "VAConfigAttribMaxPictureWidth");
    assert_eq!(VAConfigAttribMaxPictureHeight as i64, 19, "VAConfigAttribMaxPictureHeight");
    assert_eq!(VA_ATTRIB_NOT_SUPPORTED as i64, 2147483648, "VA_ATTRIB_NOT_SUPPORTED");
    assert_eq!(VA_RT_FORMAT_YUV420 as i64, 1, "VA_RT_FORMAT_YUV420");
    assert_eq!(VA_RT_FORMAT_YUV420_10 as i64, 256, "VA_RT_FORMAT_YUV420_10");
    assert_eq!(VA_PROGRESSIVE as i64, 1, "VA_PROGRESSIVE");
    assert_eq!(VAPictureParameterBufferType as i64, 0, "VAPictureParameterBufferType");
    assert_eq!(VAIQMatrixBufferType as i64, 1, "VAIQMatrixBufferType");
    assert_eq!(VASliceParameterBufferType as i64, 4, "VASliceParameterBufferType");
    assert_eq!(VASliceDataBufferType as i64, 5, "VASliceDataBufferType");
    assert_eq!(VA_SLICE_DATA_FLAG_ALL as i64, 0, "VA_SLICE_DATA_FLAG_ALL");
    assert_eq!(VA_PICTURE_H264_INVALID as i64, 1, "VA_PICTURE_H264_INVALID");
    assert_eq!(VA_PICTURE_H264_TOP_FIELD as i64, 2, "VA_PICTURE_H264_TOP_FIELD");
    assert_eq!(VA_PICTURE_H264_BOTTOM_FIELD as i64, 4, "VA_PICTURE_H264_BOTTOM_FIELD");
    assert_eq!(VA_PICTURE_H264_SHORT_TERM_REFERENCE as i64, 8, "VA_PICTURE_H264_SHORT_TERM_REFERENCE");
    assert_eq!(VA_PICTURE_H264_LONG_TERM_REFERENCE as i64, 16, "VA_PICTURE_H264_LONG_TERM_REFERENCE");
    assert_eq!(VA_FOURCC_NV12 as i64, 842094158, "VA_FOURCC_NV12");
    assert_eq!(VA_FOURCC_P010 as i64, 808530000, "VA_FOURCC_P010");
    assert_eq!(h264_seq_fields(1, false, false, true, false, true, false, 5, 2, 9, true), 419153, "seq_fields bits");
    assert_eq!(h264_pic_fields(true, false, 2, true, false, false, false, true, false, true), 1305, "pic_fields bits");
}

#[test]
fn hevc_layouts_and_constants_match_the_header() {
    assert_eq!((size_of::<VAPictureHEVC>(), align_of::<VAPictureHEVC>()), (28, 4), "VAPictureHEVC");
    assert_eq!(offset_of!(VAPictureHEVC, picture_id), 0, "VAPictureHEVC.picture_id");
    assert_eq!(offset_of!(VAPictureHEVC, pic_order_cnt), 4, "VAPictureHEVC.pic_order_cnt");
    assert_eq!(offset_of!(VAPictureHEVC, flags), 8, "VAPictureHEVC.flags");
    assert_eq!(offset_of!(VAPictureHEVC, va_reserved), 12, "VAPictureHEVC.va_reserved");
    assert_eq!((size_of::<VAPictureParameterBufferHEVC>(), align_of::<VAPictureParameterBufferHEVC>()), (604, 4), "VAPictureParameterBufferHEVC");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, CurrPic), 0, "VAPictureParameterBufferHEVC.CurrPic");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, ReferenceFrames), 28, "VAPictureParameterBufferHEVC.ReferenceFrames");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, pic_width_in_luma_samples), 448, "VAPictureParameterBufferHEVC.pic_width_in_luma_samples");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, pic_height_in_luma_samples), 450, "VAPictureParameterBufferHEVC.pic_height_in_luma_samples");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, pic_fields), 452, "VAPictureParameterBufferHEVC.pic_fields");
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, sps_max_dec_pic_buffering_minus1),
        456,
        "VAPictureParameterBufferHEVC.sps_max_dec_pic_buffering_minus1"
    );
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, bit_depth_luma_minus8), 457, "VAPictureParameterBufferHEVC.bit_depth_luma_minus8");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, bit_depth_chroma_minus8), 458, "VAPictureParameterBufferHEVC.bit_depth_chroma_minus8");
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, pcm_sample_bit_depth_luma_minus1),
        459,
        "VAPictureParameterBufferHEVC.pcm_sample_bit_depth_luma_minus1"
    );
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, pcm_sample_bit_depth_chroma_minus1),
        460,
        "VAPictureParameterBufferHEVC.pcm_sample_bit_depth_chroma_minus1"
    );
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, log2_min_luma_coding_block_size_minus3),
        461,
        "VAPictureParameterBufferHEVC.log2_min_luma_coding_block_size_minus3"
    );
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, log2_diff_max_min_luma_coding_block_size),
        462,
        "VAPictureParameterBufferHEVC.log2_diff_max_min_luma_coding_block_size"
    );
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, log2_min_transform_block_size_minus2),
        463,
        "VAPictureParameterBufferHEVC.log2_min_transform_block_size_minus2"
    );
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, log2_diff_max_min_transform_block_size),
        464,
        "VAPictureParameterBufferHEVC.log2_diff_max_min_transform_block_size"
    );
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, log2_min_pcm_luma_coding_block_size_minus3),
        465,
        "VAPictureParameterBufferHEVC.log2_min_pcm_luma_coding_block_size_minus3"
    );
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, log2_diff_max_min_pcm_luma_coding_block_size),
        466,
        "VAPictureParameterBufferHEVC.log2_diff_max_min_pcm_luma_coding_block_size"
    );
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, max_transform_hierarchy_depth_intra),
        467,
        "VAPictureParameterBufferHEVC.max_transform_hierarchy_depth_intra"
    );
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, max_transform_hierarchy_depth_inter),
        468,
        "VAPictureParameterBufferHEVC.max_transform_hierarchy_depth_inter"
    );
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, init_qp_minus26), 469, "VAPictureParameterBufferHEVC.init_qp_minus26");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, diff_cu_qp_delta_depth), 470, "VAPictureParameterBufferHEVC.diff_cu_qp_delta_depth");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, pps_cb_qp_offset), 471, "VAPictureParameterBufferHEVC.pps_cb_qp_offset");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, pps_cr_qp_offset), 472, "VAPictureParameterBufferHEVC.pps_cr_qp_offset");
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, log2_parallel_merge_level_minus2),
        473,
        "VAPictureParameterBufferHEVC.log2_parallel_merge_level_minus2"
    );
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, num_tile_columns_minus1), 474, "VAPictureParameterBufferHEVC.num_tile_columns_minus1");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, num_tile_rows_minus1), 475, "VAPictureParameterBufferHEVC.num_tile_rows_minus1");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, column_width_minus1), 476, "VAPictureParameterBufferHEVC.column_width_minus1");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, row_height_minus1), 514, "VAPictureParameterBufferHEVC.row_height_minus1");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, slice_parsing_fields), 556, "VAPictureParameterBufferHEVC.slice_parsing_fields");
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, log2_max_pic_order_cnt_lsb_minus4),
        560,
        "VAPictureParameterBufferHEVC.log2_max_pic_order_cnt_lsb_minus4"
    );
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, num_short_term_ref_pic_sets), 561, "VAPictureParameterBufferHEVC.num_short_term_ref_pic_sets");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, num_long_term_ref_pic_sps), 562, "VAPictureParameterBufferHEVC.num_long_term_ref_pic_sps");
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, num_ref_idx_l0_default_active_minus1),
        563,
        "VAPictureParameterBufferHEVC.num_ref_idx_l0_default_active_minus1"
    );
    assert_eq!(
        offset_of!(VAPictureParameterBufferHEVC, num_ref_idx_l1_default_active_minus1),
        564,
        "VAPictureParameterBufferHEVC.num_ref_idx_l1_default_active_minus1"
    );
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, pps_beta_offset_div2), 565, "VAPictureParameterBufferHEVC.pps_beta_offset_div2");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, pps_tc_offset_div2), 566, "VAPictureParameterBufferHEVC.pps_tc_offset_div2");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, num_extra_slice_header_bits), 567, "VAPictureParameterBufferHEVC.num_extra_slice_header_bits");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, st_rps_bits), 568, "VAPictureParameterBufferHEVC.st_rps_bits");
    assert_eq!(offset_of!(VAPictureParameterBufferHEVC, va_reserved), 572, "VAPictureParameterBufferHEVC.va_reserved");
    assert_eq!((size_of::<VASliceParameterBufferHEVC>(), align_of::<VASliceParameterBufferHEVC>()), (264, 4), "VASliceParameterBufferHEVC");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_data_size), 0, "VASliceParameterBufferHEVC.slice_data_size");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_data_offset), 4, "VASliceParameterBufferHEVC.slice_data_offset");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_data_flag), 8, "VASliceParameterBufferHEVC.slice_data_flag");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_data_byte_offset), 12, "VASliceParameterBufferHEVC.slice_data_byte_offset");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_segment_address), 16, "VASliceParameterBufferHEVC.slice_segment_address");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, RefPicList), 20, "VASliceParameterBufferHEVC.RefPicList");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, LongSliceFlags), 52, "VASliceParameterBufferHEVC.LongSliceFlags");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, collocated_ref_idx), 56, "VASliceParameterBufferHEVC.collocated_ref_idx");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, num_ref_idx_l0_active_minus1), 57, "VASliceParameterBufferHEVC.num_ref_idx_l0_active_minus1");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, num_ref_idx_l1_active_minus1), 58, "VASliceParameterBufferHEVC.num_ref_idx_l1_active_minus1");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_qp_delta), 59, "VASliceParameterBufferHEVC.slice_qp_delta");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_cb_qp_offset), 60, "VASliceParameterBufferHEVC.slice_cb_qp_offset");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_cr_qp_offset), 61, "VASliceParameterBufferHEVC.slice_cr_qp_offset");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_beta_offset_div2), 62, "VASliceParameterBufferHEVC.slice_beta_offset_div2");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_tc_offset_div2), 63, "VASliceParameterBufferHEVC.slice_tc_offset_div2");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, luma_log2_weight_denom), 64, "VASliceParameterBufferHEVC.luma_log2_weight_denom");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, delta_chroma_log2_weight_denom), 65, "VASliceParameterBufferHEVC.delta_chroma_log2_weight_denom");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, delta_luma_weight_l0), 66, "VASliceParameterBufferHEVC.delta_luma_weight_l0");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, luma_offset_l0), 81, "VASliceParameterBufferHEVC.luma_offset_l0");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, delta_chroma_weight_l0), 96, "VASliceParameterBufferHEVC.delta_chroma_weight_l0");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, ChromaOffsetL0), 126, "VASliceParameterBufferHEVC.ChromaOffsetL0");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, delta_luma_weight_l1), 156, "VASliceParameterBufferHEVC.delta_luma_weight_l1");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, luma_offset_l1), 171, "VASliceParameterBufferHEVC.luma_offset_l1");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, delta_chroma_weight_l1), 186, "VASliceParameterBufferHEVC.delta_chroma_weight_l1");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, ChromaOffsetL1), 216, "VASliceParameterBufferHEVC.ChromaOffsetL1");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, five_minus_max_num_merge_cand), 246, "VASliceParameterBufferHEVC.five_minus_max_num_merge_cand");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, num_entry_point_offsets), 248, "VASliceParameterBufferHEVC.num_entry_point_offsets");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, entry_offset_to_subset_array), 250, "VASliceParameterBufferHEVC.entry_offset_to_subset_array");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, slice_data_num_emu_prevn_bytes), 252, "VASliceParameterBufferHEVC.slice_data_num_emu_prevn_bytes");
    assert_eq!(offset_of!(VASliceParameterBufferHEVC, va_reserved), 256, "VASliceParameterBufferHEVC.va_reserved");
    assert_eq!((size_of::<VAIQMatrixBufferHEVC>(), align_of::<VAIQMatrixBufferHEVC>()), (1016, 4), "VAIQMatrixBufferHEVC");
    assert_eq!(offset_of!(VAIQMatrixBufferHEVC, ScalingList4x4), 0, "VAIQMatrixBufferHEVC.ScalingList4x4");
    assert_eq!(offset_of!(VAIQMatrixBufferHEVC, ScalingList8x8), 96, "VAIQMatrixBufferHEVC.ScalingList8x8");
    assert_eq!(offset_of!(VAIQMatrixBufferHEVC, ScalingList16x16), 480, "VAIQMatrixBufferHEVC.ScalingList16x16");
    assert_eq!(offset_of!(VAIQMatrixBufferHEVC, ScalingList32x32), 864, "VAIQMatrixBufferHEVC.ScalingList32x32");
    assert_eq!(offset_of!(VAIQMatrixBufferHEVC, ScalingListDC16x16), 992, "VAIQMatrixBufferHEVC.ScalingListDC16x16");
    assert_eq!(offset_of!(VAIQMatrixBufferHEVC, ScalingListDC32x32), 998, "VAIQMatrixBufferHEVC.ScalingListDC32x32");
    assert_eq!(offset_of!(VAIQMatrixBufferHEVC, va_reserved), 1000, "VAIQMatrixBufferHEVC.va_reserved");
    assert_eq!(VA_PICTURE_HEVC_INVALID as i64, 1, "VA_PICTURE_HEVC_INVALID");
    assert_eq!(VA_PICTURE_HEVC_LONG_TERM_REFERENCE as i64, 8, "VA_PICTURE_HEVC_LONG_TERM_REFERENCE");
    assert_eq!(VA_PICTURE_HEVC_RPS_ST_CURR_BEFORE as i64, 16, "VA_PICTURE_HEVC_RPS_ST_CURR_BEFORE");
    assert_eq!(VA_PICTURE_HEVC_RPS_ST_CURR_AFTER as i64, 32, "VA_PICTURE_HEVC_RPS_ST_CURR_AFTER");
    assert_eq!(VA_PICTURE_HEVC_RPS_LT_CURR as i64, 64, "VA_PICTURE_HEVC_RPS_LT_CURR");
    assert_eq!(
        pack_bits(&[
            (1, 2),
            (0, 1),
            (0, 1),
            (0, 1),
            (0, 1),
            (1, 1),
            (0, 1),
            (0, 1),
            (0, 1),
            (0, 1),
            (0, 1),
            (0, 1),
            (0, 1),
            (1, 1),
            (0, 1),
            (0, 1),
            (0, 1),
            (0, 1),
            (0, 1),
            (1, 1)
        ]),
        1065025,
        "pic_fields"
    );
    assert_eq!(
        pack_bits(&[(0, 1), (1, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (1, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (1, 1)]),
        8322,
        "slice_parsing_fields"
    );
    assert_eq!(pack_bits(&[(1, 1), (0, 1), (2, 2), (0, 2), (0, 1), (0, 1), (1, 1), (0, 1), (0, 1), (0, 1), (0, 1), (1, 1)]), 8457, "LongSliceFlags");
}

#[test]
fn h264_encode_layouts_and_constants_match_the_header() {
    assert_eq!((size_of::<VAEncSequenceParameterBufferH264>(), align_of::<VAEncSequenceParameterBufferH264>()), (1132, 4), "VAEncSequenceParameterBufferH264");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, seq_parameter_set_id), 0, "VAEncSequenceParameterBufferH264.seq_parameter_set_id");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, level_idc), 1, "VAEncSequenceParameterBufferH264.level_idc");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, intra_period), 4, "VAEncSequenceParameterBufferH264.intra_period");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, intra_idr_period), 8, "VAEncSequenceParameterBufferH264.intra_idr_period");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, ip_period), 12, "VAEncSequenceParameterBufferH264.ip_period");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, bits_per_second), 16, "VAEncSequenceParameterBufferH264.bits_per_second");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, max_num_ref_frames), 20, "VAEncSequenceParameterBufferH264.max_num_ref_frames");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, picture_width_in_mbs), 24, "VAEncSequenceParameterBufferH264.picture_width_in_mbs");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, picture_height_in_mbs), 26, "VAEncSequenceParameterBufferH264.picture_height_in_mbs");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, seq_fields), 28, "VAEncSequenceParameterBufferH264.seq_fields");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, bit_depth_luma_minus8), 32, "VAEncSequenceParameterBufferH264.bit_depth_luma_minus8");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, bit_depth_chroma_minus8), 33, "VAEncSequenceParameterBufferH264.bit_depth_chroma_minus8");
    assert_eq!(
        offset_of!(VAEncSequenceParameterBufferH264, num_ref_frames_in_pic_order_cnt_cycle),
        34,
        "VAEncSequenceParameterBufferH264.num_ref_frames_in_pic_order_cnt_cycle"
    );
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, offset_for_non_ref_pic), 36, "VAEncSequenceParameterBufferH264.offset_for_non_ref_pic");
    assert_eq!(
        offset_of!(VAEncSequenceParameterBufferH264, offset_for_top_to_bottom_field),
        40,
        "VAEncSequenceParameterBufferH264.offset_for_top_to_bottom_field"
    );
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, offset_for_ref_frame), 44, "VAEncSequenceParameterBufferH264.offset_for_ref_frame");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, frame_cropping_flag), 1068, "VAEncSequenceParameterBufferH264.frame_cropping_flag");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, frame_crop_left_offset), 1072, "VAEncSequenceParameterBufferH264.frame_crop_left_offset");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, frame_crop_right_offset), 1076, "VAEncSequenceParameterBufferH264.frame_crop_right_offset");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, frame_crop_top_offset), 1080, "VAEncSequenceParameterBufferH264.frame_crop_top_offset");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, frame_crop_bottom_offset), 1084, "VAEncSequenceParameterBufferH264.frame_crop_bottom_offset");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, vui_parameters_present_flag), 1088, "VAEncSequenceParameterBufferH264.vui_parameters_present_flag");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, vui_fields), 1092, "VAEncSequenceParameterBufferH264.vui_fields");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, aspect_ratio_idc), 1096, "VAEncSequenceParameterBufferH264.aspect_ratio_idc");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, sar_width), 1100, "VAEncSequenceParameterBufferH264.sar_width");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, sar_height), 1104, "VAEncSequenceParameterBufferH264.sar_height");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, num_units_in_tick), 1108, "VAEncSequenceParameterBufferH264.num_units_in_tick");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, time_scale), 1112, "VAEncSequenceParameterBufferH264.time_scale");
    assert_eq!(offset_of!(VAEncSequenceParameterBufferH264, va_reserved), 1116, "VAEncSequenceParameterBufferH264.va_reserved");
    assert_eq!((size_of::<VAEncPictureParameterBufferH264>(), align_of::<VAEncPictureParameterBufferH264>()), (648, 4), "VAEncPictureParameterBufferH264");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, CurrPic), 0, "VAEncPictureParameterBufferH264.CurrPic");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, ReferenceFrames), 36, "VAEncPictureParameterBufferH264.ReferenceFrames");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, coded_buf), 612, "VAEncPictureParameterBufferH264.coded_buf");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, pic_parameter_set_id), 616, "VAEncPictureParameterBufferH264.pic_parameter_set_id");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, seq_parameter_set_id), 617, "VAEncPictureParameterBufferH264.seq_parameter_set_id");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, last_picture), 618, "VAEncPictureParameterBufferH264.last_picture");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, frame_num), 620, "VAEncPictureParameterBufferH264.frame_num");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, pic_init_qp), 622, "VAEncPictureParameterBufferH264.pic_init_qp");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, num_ref_idx_l0_active_minus1), 623, "VAEncPictureParameterBufferH264.num_ref_idx_l0_active_minus1");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, num_ref_idx_l1_active_minus1), 624, "VAEncPictureParameterBufferH264.num_ref_idx_l1_active_minus1");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, chroma_qp_index_offset), 625, "VAEncPictureParameterBufferH264.chroma_qp_index_offset");
    assert_eq!(
        offset_of!(VAEncPictureParameterBufferH264, second_chroma_qp_index_offset),
        626,
        "VAEncPictureParameterBufferH264.second_chroma_qp_index_offset"
    );
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, pic_fields), 628, "VAEncPictureParameterBufferH264.pic_fields");
    assert_eq!(offset_of!(VAEncPictureParameterBufferH264, va_reserved), 632, "VAEncPictureParameterBufferH264.va_reserved");
    assert_eq!((size_of::<VAEncSliceParameterBufferH264>(), align_of::<VAEncSliceParameterBufferH264>()), (3140, 4), "VAEncSliceParameterBufferH264");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, macroblock_address), 0, "VAEncSliceParameterBufferH264.macroblock_address");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, num_macroblocks), 4, "VAEncSliceParameterBufferH264.num_macroblocks");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, macroblock_info), 8, "VAEncSliceParameterBufferH264.macroblock_info");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, slice_type), 12, "VAEncSliceParameterBufferH264.slice_type");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, pic_parameter_set_id), 13, "VAEncSliceParameterBufferH264.pic_parameter_set_id");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, idr_pic_id), 14, "VAEncSliceParameterBufferH264.idr_pic_id");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, pic_order_cnt_lsb), 16, "VAEncSliceParameterBufferH264.pic_order_cnt_lsb");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, delta_pic_order_cnt_bottom), 20, "VAEncSliceParameterBufferH264.delta_pic_order_cnt_bottom");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, delta_pic_order_cnt), 24, "VAEncSliceParameterBufferH264.delta_pic_order_cnt");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, direct_spatial_mv_pred_flag), 32, "VAEncSliceParameterBufferH264.direct_spatial_mv_pred_flag");
    assert_eq!(
        offset_of!(VAEncSliceParameterBufferH264, num_ref_idx_active_override_flag),
        33,
        "VAEncSliceParameterBufferH264.num_ref_idx_active_override_flag"
    );
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, num_ref_idx_l0_active_minus1), 34, "VAEncSliceParameterBufferH264.num_ref_idx_l0_active_minus1");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, num_ref_idx_l1_active_minus1), 35, "VAEncSliceParameterBufferH264.num_ref_idx_l1_active_minus1");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, RefPicList0), 36, "VAEncSliceParameterBufferH264.RefPicList0");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, RefPicList1), 1188, "VAEncSliceParameterBufferH264.RefPicList1");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, luma_log2_weight_denom), 2340, "VAEncSliceParameterBufferH264.luma_log2_weight_denom");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, chroma_log2_weight_denom), 2341, "VAEncSliceParameterBufferH264.chroma_log2_weight_denom");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, luma_weight_l0_flag), 2342, "VAEncSliceParameterBufferH264.luma_weight_l0_flag");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, luma_weight_l0), 2344, "VAEncSliceParameterBufferH264.luma_weight_l0");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, luma_offset_l0), 2408, "VAEncSliceParameterBufferH264.luma_offset_l0");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, chroma_weight_l0_flag), 2472, "VAEncSliceParameterBufferH264.chroma_weight_l0_flag");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, chroma_weight_l0), 2474, "VAEncSliceParameterBufferH264.chroma_weight_l0");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, chroma_offset_l0), 2602, "VAEncSliceParameterBufferH264.chroma_offset_l0");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, luma_weight_l1_flag), 2730, "VAEncSliceParameterBufferH264.luma_weight_l1_flag");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, luma_weight_l1), 2732, "VAEncSliceParameterBufferH264.luma_weight_l1");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, luma_offset_l1), 2796, "VAEncSliceParameterBufferH264.luma_offset_l1");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, chroma_weight_l1_flag), 2860, "VAEncSliceParameterBufferH264.chroma_weight_l1_flag");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, chroma_weight_l1), 2862, "VAEncSliceParameterBufferH264.chroma_weight_l1");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, chroma_offset_l1), 2990, "VAEncSliceParameterBufferH264.chroma_offset_l1");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, cabac_init_idc), 3118, "VAEncSliceParameterBufferH264.cabac_init_idc");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, slice_qp_delta), 3119, "VAEncSliceParameterBufferH264.slice_qp_delta");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, disable_deblocking_filter_idc), 3120, "VAEncSliceParameterBufferH264.disable_deblocking_filter_idc");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, slice_alpha_c0_offset_div2), 3121, "VAEncSliceParameterBufferH264.slice_alpha_c0_offset_div2");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, slice_beta_offset_div2), 3122, "VAEncSliceParameterBufferH264.slice_beta_offset_div2");
    assert_eq!(offset_of!(VAEncSliceParameterBufferH264, va_reserved), 3124, "VAEncSliceParameterBufferH264.va_reserved");
    assert_eq!((size_of::<VAEncMiscParameterRateControl>(), align_of::<VAEncMiscParameterRateControl>()), (60, 4), "VAEncMiscParameterRateControl");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, bits_per_second), 0, "VAEncMiscParameterRateControl.bits_per_second");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, target_percentage), 4, "VAEncMiscParameterRateControl.target_percentage");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, window_size), 8, "VAEncMiscParameterRateControl.window_size");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, initial_qp), 12, "VAEncMiscParameterRateControl.initial_qp");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, min_qp), 16, "VAEncMiscParameterRateControl.min_qp");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, basic_unit_size), 20, "VAEncMiscParameterRateControl.basic_unit_size");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, rc_flags), 24, "VAEncMiscParameterRateControl.rc_flags");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, ICQ_quality_factor), 28, "VAEncMiscParameterRateControl.ICQ_quality_factor");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, max_qp), 32, "VAEncMiscParameterRateControl.max_qp");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, quality_factor), 36, "VAEncMiscParameterRateControl.quality_factor");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, target_frame_size), 40, "VAEncMiscParameterRateControl.target_frame_size");
    assert_eq!(offset_of!(VAEncMiscParameterRateControl, va_reserved), 44, "VAEncMiscParameterRateControl.va_reserved");
    assert_eq!((size_of::<VAEncMiscParameterFrameRate>(), align_of::<VAEncMiscParameterFrameRate>()), (24, 4), "VAEncMiscParameterFrameRate");
    assert_eq!(offset_of!(VAEncMiscParameterFrameRate, framerate), 0, "VAEncMiscParameterFrameRate.framerate");
    assert_eq!(offset_of!(VAEncMiscParameterFrameRate, framerate_flags), 4, "VAEncMiscParameterFrameRate.framerate_flags");
    assert_eq!(offset_of!(VAEncMiscParameterFrameRate, va_reserved), 8, "VAEncMiscParameterFrameRate.va_reserved");
    assert_eq!((size_of::<VAEncMiscParameterHRD>(), align_of::<VAEncMiscParameterHRD>()), (24, 4), "VAEncMiscParameterHRD");
    assert_eq!(offset_of!(VAEncMiscParameterHRD, initial_buffer_fullness), 0, "VAEncMiscParameterHRD.initial_buffer_fullness");
    assert_eq!(offset_of!(VAEncMiscParameterHRD, buffer_size), 4, "VAEncMiscParameterHRD.buffer_size");
    assert_eq!(offset_of!(VAEncMiscParameterHRD, va_reserved), 8, "VAEncMiscParameterHRD.va_reserved");
    assert_eq!((size_of::<VACodedBufferSegment>(), align_of::<VACodedBufferSegment>()), (48, 8), "VACodedBufferSegment");
    assert_eq!(offset_of!(VACodedBufferSegment, size), 0, "VACodedBufferSegment.size");
    assert_eq!(offset_of!(VACodedBufferSegment, bit_offset), 4, "VACodedBufferSegment.bit_offset");
    assert_eq!(offset_of!(VACodedBufferSegment, status), 8, "VACodedBufferSegment.status");
    assert_eq!(offset_of!(VACodedBufferSegment, reserved), 12, "VACodedBufferSegment.reserved");
    assert_eq!(offset_of!(VACodedBufferSegment, buf), 16, "VACodedBufferSegment.buf");
    assert_eq!(offset_of!(VACodedBufferSegment, next), 24, "VACodedBufferSegment.next");
    assert_eq!(offset_of!(VACodedBufferSegment, va_reserved), 32, "VACodedBufferSegment.va_reserved");
    assert_eq!(offset_of!(VAEncMisc<VAEncMiscParameterRateControl>, data), 4, "misc data");
    assert_eq!(VAEntrypointEncSlice as i64, 6, "VAEntrypointEncSlice");
    assert_eq!(VAConfigAttribRateControl as i64, 5, "VAConfigAttribRateControl");
    assert_eq!(VAConfigAttribEncPackedHeaders as i64, 10, "VAConfigAttribEncPackedHeaders");
    assert_eq!(VA_RC_CBR as i64, 2, "VA_RC_CBR");
    assert_eq!(VA_RC_VBR as i64, 4, "VA_RC_VBR");
    assert_eq!(VA_RC_CQP as i64, 16, "VA_RC_CQP");
    assert_eq!(VAEncCodedBufferType as i64, 21, "VAEncCodedBufferType");
    assert_eq!(VAEncSequenceParameterBufferType as i64, 22, "VAEncSequenceParameterBufferType");
    assert_eq!(VAEncPictureParameterBufferType as i64, 23, "VAEncPictureParameterBufferType");
    assert_eq!(VAEncSliceParameterBufferType as i64, 24, "VAEncSliceParameterBufferType");
    assert_eq!(VAEncMiscParameterBufferType as i64, 27, "VAEncMiscParameterBufferType");
    assert_eq!(VAEncMiscParameterTypeFrameRate as i64, 0, "VAEncMiscParameterTypeFrameRate");
    assert_eq!(VAEncMiscParameterTypeRateControl as i64, 1, "VAEncMiscParameterTypeRateControl");
    assert_eq!(VAEncMiscParameterTypeHRD as i64, 5, "VAEncMiscParameterTypeHRD");
    assert_eq!(pack_bits(&[(1, 2), (1, 1), (0, 1), (0, 1), (1, 1), (4, 4), (2, 2), (3, 4), (0, 1)]), 14629, "enc seq_fields");
    assert_eq!(pack_bits(&[(0, 1), (1, 1), (0, 1), (15, 5), (0, 5), (1, 1), (0, 1), (0, 1)]), 8314, "enc vui_fields");
    assert_eq!(pack_bits(&[(1, 1), (1, 2), (1, 1), (0, 1), (0, 2), (0, 1), (1, 1), (1, 1), (0, 1), (0, 1), (0, 1)]), 779, "enc pic_fields");
}
